### ISSUE TITLE
ARM Build

### ISSUE THREAD

**Issue by amraln** [appvantageasia/html2pdf-service#176]
**Is your feature request related to a problem? Please describe.**
ARM build has been setup in repository, the last PR is #173 

But from what I saw in github actions itself there is some issue about it: https://github.com/actions/runner-images/issues/2552,
And there is a feature request too: https://github.com/actions/runner-images/issues/5631

**Describe the solution you'd like**
I guess dropping the github action build ARM pipeline for now? So, that it won't break the main amd image pipeline

**Describe alternatives you've considered**
No other solution yet

**Additional context**
Keeping the dockerbuild for ARM might help locally build docker on arm based (m1).

**Comment by amraln** [comment]
Closing this issue, as it already have automation for ARM build

- #201

**Comment by frayhan94** [comment]
Cool

Kam, 12 Okt 2023 pukul 11.23 Amral Nazar ***@***.***> menulis:
